### ISSUE TITLE
running rust role as a non-root user fails

### ISSUE THREAD

**Issue by jkryl** [fubarhouse/ansible-role-rust#15]
Maybe I'm missing something obvious, but I'm trying to install rust for ssh user which ansible is using to connect to the host and it fails when doing apt cache update:
```
TASK [fubarhouse.rust : Rust | Update apt cache] *******************************
fatal: [mayastor-dev]: FAILED! => {"changed": false, "msg": "Failed to lock apt for exclusive operation"}
```
If I run the role with "become: true" (root), then rust is installed for the root user and not for the one I want.

btw isn't the apt-cache update step completely useless when rust is installed using rustup script and not by the packaging system?

**Comment by fubarhouse** [comment]
@jkryl,

It's an interesting idea - I'll see if the role tests well without the task and get back to you.

**Comment by jkryl** [comment]
it works but I had to rewrite the condition as follows:
```
  when:
    - ansible_os_family == "Debian"
    - '"curl" not in rust_which_curl.stdout or "gcc" not in rust_which_gcc.stdout'
```
The form with parenthesis and "and" did not work for me. Thanks!

**Comment by fubarhouse** [comment]
The tests are beginning to pass so this should be merged tonight - they run for a while and there would be three: push, PR and merge. I'll update this one after it's merged.

**Comment by jkryl** [comment]
no rush, it can wait. Thanks for all the work!
